### ISSUE TITLE
docker ssh 블로그 글 ssh 동작 문제

### ISSUE THREAD

**Issue by CEOmurky** [kukaro/Eris-DockerExampleTemplate#1]
[docker ssh 블로그 글](https://kamang-it.tistory.com/entry/DockerUbuntuSshd-%EC%9A%B0%EB%B6%84%ED%88%AC-%EC%BB%A8%ED%85%8C%EC%9D%B4%EB%84%88-%EC%8B%A4%ED%96%89%ED%95%98%EA%B3%A0-%EC%9B%90%EA%B2%A9%EC%A0%91%EC%86%8D%ED%95%98%EA%B8%B0ssh)

댓글을 남기려 했는데 tistory는 댓글이 안남겨지네요 ㅠㅠ

그래서 이슈로 등록합니다

위의 방법해서 접속이 안되어서 해당 컨테이너에 'service ssh restart' 를 해주니 잘 동작합니다.

굳이 attach 안하고 하려면 `docker exec {컨테이너이름} service ssh start` 해주셔도 될것 같습니다

또는 Dockerfile에 RUN service ssh restart 추가해줘도 될것 같습니다.

좋은 글 감사합니다.

**Comment by kukaro** [comment]
어떤부분이 안된다고 하시는지 잘 모르겠습니다만 저건 제가 따로 작성한 Dockerfile이 아니며 추천수가 가장 높고 소스가 open되어있는 dockerfile을 제가 복사해서 해석한것에 불과합니다. 뭐 되는 방법으로 하시면 되겠지만 다시 테스트 해봤지만 저는 문제없이 실행이 됩니다.

https://hub.docker.com/r/rastasheep/ubuntu-sshd/dockerfile
해당 허브에서 전 참고하였고 다운로드수는 백만을 넘어섰으니 어느정도 안정성은 검증됬으리라 판단됩니다.
편한 방법으로 하시면 되겠지만 만약 제대로 되지 않으셨다면 (도커 자체가 명령어를 최대한 안쓰는 쪽으로를 권장하기 때문에) 문제의 원인을 판단해 보시는것을 추천드립니다.

부족한 포스팅에 좋은 답글 남겨주셔서 감사합니다.

**Comment by CEOmurky** [comment]
해당 도커 파일대로 컨테이너를 생성하면 ssh 서비스는 함께 설치되지만 service에 등록이 되어있지 않아서 외부에서 접속이 안된다는 것을 의미했습니다.

긴 답변 감사합니다.

위의 블로그 덕분에 잘 쓰고 있습니다.
